# AUTO-GENERATED by @keewano/codegen.
# DO NOT EDIT. Re-run `npx keewano-codegen --target python --output <path of this file>` to regenerate.
# Formatters and linters should skip it (black, ruff, flake8).
#
# Events (sorted by id, as the definition files carry them):
#   2500  SaveWorld  (None)
#   2501  SolveHunger  (Bool)

from keewano_sdk import CustomEventSet, KeewanoCodegen

CUSTOM_EVENT_SET = CustomEventSet.from_gzip_base64(
    version=2814510538,
    event_count=2,
    gzip_base64="H4sIAAAAAAAA/zvCyRmcWJYanl+Uk8LAcJSTOzg/pyzVozQvPbWImQEAH2856R4AAAA=",
)


def report_save_world() -> None:
    KeewanoCodegen.report_custom_event(2500)


def report_solve_hunger(value: bool) -> None:
    KeewanoCodegen.report_custom_event_bool(2501, value)
